### PR TITLE
Float arg

### PR DESCRIPTION
**Pull request by rknLA**
FloatArgument, for floating point args that need a range.

Still needs unit tests, but at this point, so does everything.

### CODE REVIEW

**Comment by rknLA** [comment]
Also, this and IntegerArgument could probably share a base argument type, since most of the range checking is the same.  The main difference is that the text from the request body is cast to a float instead of to an int.

**Comment by soundofjw** [comment]
Looks good to me.
As a side thought, `DecimalArgument` ?

**Comment by rknLA** [comment]
Hmm, yeah, interesting thought indeed. I think `DecimalArgument` makes sense, since this data will most likely be transmitted as a string rather than an IEEE 754 binary float, but that then begs the question...

Why do you think `DecimalArgument` is better than `FloatArgument`?

**Comment by rknLA** [comment]
@soundofjw I'm going to leave this as `FloatArgument` for now, because the value type on the python end is `float`.

**Pull request merged**
